//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yifei.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YFPLUS_Client
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string ClientIdentify { get; set; }
        public string ClientSecret { get; set; }
        public string RedirectUrl { get; set; }
    }
}
